# Generated by Django 5.0.10 on 2026-01-08 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('User_ID', models.CharField(max_length=50, unique=True, verbose_name='User ID')),
                ('Email_ID', models.EmailField(max_length=254, unique=True, verbose_name='Email ID')),
                ('Password', models.CharField(max_length=255, verbose_name='Hashed Password')),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10, verbose_name='User Role')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'db_table': 'UserDevice',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('User_ID', models.CharField(max_length=50, verbose_name='User ID')),
                ('Device_ID', models.CharField(max_length=50, unique=True, verbose_name='Device ID')),
                ('Latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'Device',
                'indexes': [models.Index(fields=['User_ID'], name='Device_User_ID_862d47_idx'), models.Index(fields=['Device_ID'], name='Device_Device__28b35d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('Device_ID', models.CharField(max_length=50, verbose_name='Device ID')),
                ('Temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pH', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('EC', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Electrical Conductivity')),
                ('Humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Nitrogen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Phosphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Light_Hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('Moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Reading_Date', models.DateField(default=django.utils.timezone.now)),
                ('Reading_Time', models.TimeField(default=django.utils.timezone.now)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensor Value',
                'verbose_name_plural': 'Sensor Values',
                'db_table': 'SensorValue',
                'indexes': [models.Index(fields=['Device_ID'], name='SensorValue_Device__c199a1_idx'), models.Index(fields=['Reading_Date'], name='SensorValue_Reading_46eb78_idx')],
            },
        ),
    ]
