# Generated by Django 5.0.10

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0002_sensor_reading'), 
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='Device',
        ),
        migrations.AlterModelTable(
            name='sensorvalue',
            table='SensorValue',
        ),
        migrations.AlterModelTable(
            name='userdevice',
            table='UserDevice',
        ),
        # Use RenameField instead of Remove+Add to preserve the column
        migrations.RenameField(
            model_name='device',
            old_name='User_ID',
            new_name='user',
        ),
        # Update type to ForeignKey, explicitly pointing to the existing column
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(
                db_column='User_ID',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='devices',
                to='hydroponics.userdevice',
                to_field='User_ID',
                verbose_name='User (Owner)'
            ),
        ),
    ]
