# Generated by Django 5.0.10 on 2026-01-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0003_alter_device_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorvalue',
            options={'managed': False},
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='Device_User_ID_862d47_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='sensor_read_device__d5c8e2_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='device_Device__079fcf_idx',
            old_name='Device_Device__28b35d_idx',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='device_id',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='device',
            field=models.ForeignKey(
                db_column='device_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='readings',
                to='hydroponics.device',
                to_field='Device_ID',
                verbose_name='Device'
            ),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user'], name='device_User_ID_7aaafc_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', '-timestamp'], name='sensor_read_device__7d1253_idx'),
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
        migrations.AlterModelTable(
            name='userdevice',
            table='userdevice',
        ),
    ]
