# Generated by Django 5.2.8 on 2026-01-23 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0005_fix_device_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='device_number',
            field=models.IntegerField(blank=True, help_text='Sequential number per user (e.g., 1, 2, 3)', null=True, verbose_name='Device Number'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Device owner - NULL means unclaimed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_devices', to=settings.AUTH_USER_MODEL, verbose_name='Owner (User)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, db_column='User_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hydroponics.userdevice', to_field='User_ID', verbose_name='User (Owner - Legacy)'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['owner'], name='device_owner_i_51345f_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'device_number'), name='unique_device_per_user'),
        ),
        migrations.AlterModelTable(
            name='sensorvalue',
            table='sensor_value',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
