# Generated by Django 5.0.10 on 2026-01-28 11:21

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0007_add_user_name'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='device',
        #     name='unique_device_per_user',
        # ),
        # migrations.RemoveIndex(
        #     model_name='device',
        #     name='device_owner_i_51345f_idx',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='device',
        #     unique_together={('user', 'Device_ID')},
        # ),
        migrations.AddField(
            model_name='userdevice',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        # migrations.AlterField(
        #     model_name='device',
        #     name='Device_ID',
        #     field=models.CharField(max_length=50, verbose_name='Device ID'),
        # ),
        # migrations.AlterField(
        #     model_name='device',
        #     name='user',
        #     field=models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hydroponics.userdevice', to_field='User_ID', verbose_name='User (Owner)'),
        # ),
        # migrations.RemoveField(
        #     model_name='device',
        #     name='device_number',
        # ),
        # migrations.RemoveField(
        #     model_name='device',
        #     name='owner',
        # ),
    ]
