# Generated by Django 5.2.8 on 2026-02-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0009_add_sensorvalue_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_device_per_user',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='device_owner_i_51345f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'Device_ID', 'device_type')},
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('AIR', 'Air Sensor Device'), ('WATER', 'Water Sensor Device')], help_text='Select device type: Air or Water sensor', max_length=10, null=True, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Device_ID',
            field=models.CharField(max_length=50, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hydroponics.userdevice', to_field='User_ID', verbose_name='User (Owner)'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='device_device__4f75d1_idx'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
    ]
