# Generated by Django 5.0.10 on 2026-02-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0012_add_device_sensors_and_co2'),
    ]

    operations = [
    ]
