# Generated by Django 5.2.8 on 2026-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, help_text='Short user identifier (e.g., USR001, ADM001)', max_length=10, unique=True, verbose_name='User Code'),
        ),
    ]
